name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies and run postinstall
        run: npm install
      - name: Compile Witnet data requests
        run: npm run compile:requests
      - name: Download witnet_toolkit
        run: touch node_modules/witnet-requests/assets/witnet_toolkit-x86_64-unknown-linux-gnu && npx witnet-toolkit update
      - name: Try data request
        run: npm run try
      - name: Compile Solidity contracts
        run: npm run compile:contracts
      - name: Try local migration
        run: npm run migrate
      - name: Run tests
        run: npm test
